/**
 * Dashboard templates — the 5 Phase 1 starter templates locked in
 * UX-SPEC §13. Each describes its required field roles and the
 * widgets that consume them. The smart-fill mapper resolves roles
 * against the tenant's Data Model and synthesizes a real dashboard.
 */
import type { DashboardTemplate } from "./types";

export const DASHBOARD_TEMPLATES: DashboardTemplate[] = [
  {
    id: "executive",
    title: "Executive overview",
    description:
      "Four headline KPIs · revenue trend · top-N table · geo map. Universal.",
    folder: "Executive",
    fieldRoles: [
      {
        id: "primary_measure",
        label: "Primary metric",
        hint: "Numeric column to sum (revenue, amount, value).",
        kind: "measure",
        acceptedTypes: ["currency", "float", "integer"],
        preferredNames: ["revenue", "amount", "total", "value", "price"],
      },
      {
        id: "time",
        label: "Time axis",
        hint: "Date or datetime column for the trend chart.",
        kind: "time",
        acceptedTypes: ["date", "datetime"],
        preferredNames: [
          "created_at",
          "date",
          "occurred_at",
          "transaction_date",
        ],
      },
      {
        id: "category",
        label: "Top-N category",
        hint: "Categorical column for the breakdown chart and table.",
        kind: "dimension",
        acceptedTypes: ["string", "category"],
        preferredNames: ["category", "product", "segment", "type"],
      },
      {
        id: "geo",
        label: "Geographic column",
        hint: "Country / region / state — drives the choropleth.",
        kind: "geo",
        preferredNames: ["country", "region", "state"],
        optional: true,
      },
    ],
    widgets: [
      {
        id: "kpi-total",
        title: "Total {primary_measure}",
        widgetType: "kpi-card",
        span: { cols: 1, rows: 1 },
        roles: { measure: "primary_measure" },
        agg: "sum",
      },
      {
        id: "kpi-count",
        title: "Records",
        widgetType: "big-number",
        span: { cols: 1, rows: 1 },
        roles: {},
        agg: "count",
      },
      {
        id: "kpi-avg",
        title: "Average {primary_measure}",
        widgetType: "kpi-card",
        span: { cols: 1, rows: 1 },
        roles: { measure: "primary_measure" },
        agg: "avg",
      },
      {
        id: "kpi-categories",
        title: "Distinct {category}",
        widgetType: "big-number",
        span: { cols: 1, rows: 1 },
        roles: { dimension: "category" },
        agg: "count",
      },
      {
        id: "trend",
        title: "{primary_measure} over time",
        widgetType: "line",
        span: { cols: 2, rows: 2 },
        roles: { measure: "primary_measure", time: "time" },
        agg: "sum",
      },
      {
        id: "top-categories",
        title: "{primary_measure} by {category}",
        widgetType: "bar",
        span: { cols: 2, rows: 2 },
        roles: { measure: "primary_measure", dimension: "category" },
        agg: "sum",
      },
      {
        id: "geo",
        title: "{primary_measure} by {geo}",
        widgetType: "choropleth",
        span: { cols: 2, rows: 2 },
        roles: { measure: "primary_measure", geo: "geo" },
        agg: "sum",
      },
    ],
  },

  {
    id: "sales-pipeline",
    title: "Sales pipeline",
    description:
      "Pipeline funnel · win-rate trend · top reps table · forecast. Common in B2B.",
    folder: "Sales",
    fieldRoles: [
      {
        id: "deal_value",
        label: "Deal value",
        hint: "Numeric currency column on each deal/opportunity.",
        kind: "measure",
        acceptedTypes: ["currency", "float", "integer"],
        preferredNames: ["amount", "deal_value", "value", "revenue", "arr"],
      },
      {
        id: "stage",
        label: "Pipeline stage",
        hint: "Categorical column tracking funnel position.",
        kind: "dimension",
        acceptedTypes: ["string", "category"],
        preferredNames: ["stage", "status", "phase"],
      },
      {
        id: "rep",
        label: "Sales rep",
        hint: "Categorical column for rep / owner / account exec.",
        kind: "dimension",
        acceptedTypes: ["string", "category"],
        preferredNames: ["rep", "owner", "account_exec", "salesperson"],
        optional: true,
      },
      {
        id: "close_date",
        label: "Close date",
        hint: "Date column for the win-rate trend.",
        kind: "time",
        acceptedTypes: ["date", "datetime"],
        preferredNames: ["close_date", "closed_at", "won_at", "date"],
      },
    ],
    widgets: [
      {
        id: "kpi-pipeline-value",
        title: "Pipeline value",
        widgetType: "kpi-card",
        span: { cols: 1, rows: 1 },
        roles: { measure: "deal_value" },
        agg: "sum",
      },
      {
        id: "kpi-deals",
        title: "Open deals",
        widgetType: "big-number",
        span: { cols: 1, rows: 1 },
        roles: {},
        agg: "count",
      },
      {
        id: "stage-bar",
        title: "{deal_value} by {stage}",
        widgetType: "bar",
        span: { cols: 2, rows: 2 },
        roles: { measure: "deal_value", dimension: "stage" },
        agg: "sum",
      },
      {
        id: "stage-share",
        title: "Stage distribution",
        widgetType: "donut",
        span: { cols: 2, rows: 2 },
        roles: { dimension: "stage" },
        agg: "count",
      },
      {
        id: "trend",
        title: "{deal_value} won over time",
        widgetType: "line",
        span: { cols: 2, rows: 2 },
        roles: { measure: "deal_value", time: "close_date" },
        agg: "sum",
      },
      {
        id: "top-reps",
        title: "Top {rep}",
        widgetType: "bar",
        span: { cols: 2, rows: 2 },
        roles: { measure: "deal_value", dimension: "rep" },
        agg: "sum",
      },
    ],
  },

  {
    id: "marketing",
    title: "Marketing performance",
    description:
      "Channel mix · campaigns table · conversion funnel · weekly trend.",
    folder: "Marketing",
    fieldRoles: [
      {
        id: "spend",
        label: "Spend or revenue",
        hint: "Numeric column to sum.",
        kind: "measure",
        acceptedTypes: ["currency", "float", "integer"],
        preferredNames: ["spend", "cost", "revenue", "amount"],
      },
      {
        id: "channel",
        label: "Channel / source",
        hint: "Categorical column — paid, organic, email, etc.",
        kind: "dimension",
        acceptedTypes: ["string", "category"],
        preferredNames: ["channel", "source", "medium", "campaign"],
      },
      {
        id: "time",
        label: "Time axis",
        hint: "Date column for weekly trend.",
        kind: "time",
        acceptedTypes: ["date", "datetime"],
        preferredNames: ["date", "created_at", "occurred_at"],
      },
    ],
    widgets: [
      {
        id: "kpi-spend",
        title: "Total {spend}",
        widgetType: "kpi-card",
        span: { cols: 1, rows: 1 },
        roles: { measure: "spend" },
        agg: "sum",
      },
      {
        id: "kpi-events",
        title: "Total events",
        widgetType: "big-number",
        span: { cols: 1, rows: 1 },
        roles: {},
        agg: "count",
      },
      {
        id: "channel-share",
        title: "Channel mix",
        widgetType: "donut",
        span: { cols: 2, rows: 2 },
        roles: { dimension: "channel" },
        agg: "count",
      },
      {
        id: "channel-bar",
        title: "{spend} by {channel}",
        widgetType: "bar",
        span: { cols: 2, rows: 2 },
        roles: { measure: "spend", dimension: "channel" },
        agg: "sum",
      },
      {
        id: "trend",
        title: "{spend} over time",
        widgetType: "line",
        span: { cols: 2, rows: 2 },
        roles: { measure: "spend", time: "time" },
        agg: "sum",
      },
    ],
  },

  {
    id: "operations",
    title: "Operations / health",
    description:
      "Uptime · p99 latency · error rate · top failures. Common in tech.",
    folder: "Engineering",
    fieldRoles: [
      {
        id: "duration",
        label: "Latency / duration",
        hint: "Numeric column representing milliseconds or seconds.",
        kind: "measure",
        acceptedTypes: ["integer", "float"],
        preferredNames: ["latency", "duration", "ms", "elapsed"],
      },
      {
        id: "status",
        label: "Status / error",
        hint: "Categorical column tracking success / error / status.",
        kind: "dimension",
        acceptedTypes: ["string", "category"],
        preferredNames: ["status", "error", "result", "outcome"],
      },
      {
        id: "time",
        label: "Time axis",
        hint: "Datetime column for the trend.",
        kind: "time",
        acceptedTypes: ["date", "datetime"],
        preferredNames: ["timestamp", "occurred_at", "created_at", "ts"],
      },
    ],
    widgets: [
      {
        id: "kpi-events",
        title: "Events",
        widgetType: "big-number",
        span: { cols: 1, rows: 1 },
        roles: {},
        agg: "count",
      },
      {
        id: "kpi-avg-duration",
        title: "Avg {duration}",
        widgetType: "kpi-card",
        span: { cols: 1, rows: 1 },
        roles: { measure: "duration" },
        agg: "avg",
      },
      {
        id: "trend",
        title: "{duration} over time",
        widgetType: "line",
        span: { cols: 2, rows: 2 },
        roles: { measure: "duration", time: "time" },
        agg: "avg",
      },
      {
        id: "status-share",
        title: "{status} share",
        widgetType: "donut",
        span: { cols: 2, rows: 2 },
        roles: { dimension: "status" },
        agg: "count",
      },
      {
        id: "status-table",
        title: "Top {status}",
        widgetType: "bar",
        span: { cols: 2, rows: 2 },
        roles: { dimension: "status" },
        agg: "count",
      },
    ],
  },

  {
    id: "saas",
    title: "Customer engagement / SaaS metrics",
    description:
      "Active users sparkline · activation funnel · retention cohort · feature adoption.",
    folder: "Product",
    fieldRoles: [
      {
        id: "user_id",
        label: "User identifier",
        hint: "Column that uniquely identifies a user/customer.",
        kind: "dimension",
        acceptedTypes: ["string", "integer", "category"],
        preferredNames: ["user_id", "customer_id", "account_id"],
      },
      {
        id: "event",
        label: "Event / feature",
        hint: "Categorical column naming the action / feature.",
        kind: "dimension",
        acceptedTypes: ["string", "category"],
        preferredNames: ["event", "event_type", "feature", "action"],
      },
      {
        id: "time",
        label: "Time axis",
        hint: "Datetime column.",
        kind: "time",
        acceptedTypes: ["date", "datetime"],
        preferredNames: ["occurred_at", "created_at", "timestamp"],
      },
    ],
    widgets: [
      {
        id: "kpi-events",
        title: "Total events",
        widgetType: "big-number",
        span: { cols: 1, rows: 1 },
        roles: {},
        agg: "count",
      },
      {
        id: "kpi-users",
        title: "Active {user_id}",
        widgetType: "big-number",
        span: { cols: 1, rows: 1 },
        roles: { dimension: "user_id" },
        agg: "count",
      },
      {
        id: "trend",
        title: "Events over time",
        widgetType: "line",
        span: { cols: 2, rows: 2 },
        roles: { time: "time" },
        agg: "count",
      },
      {
        id: "feature-bar",
        title: "Top {event}",
        widgetType: "bar",
        span: { cols: 2, rows: 2 },
        roles: { dimension: "event" },
        agg: "count",
      },
      {
        id: "feature-share",
        title: "{event} share",
        widgetType: "donut",
        span: { cols: 2, rows: 2 },
        roles: { dimension: "event" },
        agg: "count",
      },
    ],
  },
];

export function getTemplate(id: string): DashboardTemplate | undefined {
  return DASHBOARD_TEMPLATES.find((t) => t.id === id);
}
