/**
 * Dashboard runtime types — Phase 1 frontend mirror of the persisted
 * shape we'll land in the backend later. The dashboard view + list +
 * smart-fill output all conform to this shape so a single store can
 * back every surface.
 */

export type DashboardWidgetKind =
  | "kpi-card"
  | "big-number"
  | "line"
  | "column"
  | "bar"
  | "donut"
  | "pie"
  | "choropleth"
  | "table";

export interface DashboardWidget {
  id: string;
  title: string;
  kind: DashboardWidgetKind;
  /** Where the widget sits on the 4-column grid. */
  span: { cols: 1 | 2 | 3 | 4; rows: 1 | 2 };
  /** Plain-English description of the data it shows — cited in AI replies
   *  and shown in the smart-fill preview before generation. */
  source: string;
  /** Optional aggregation — informs the live preview formatter later. */
  agg?: "sum" | "count" | "count_distinct" | "avg" | "min" | "max";
  /** Optional table reference — set when the widget has a real source. */
  table?: { id: string };
  /** Resolved column references the widget reads (role → column). */
  fields?: Partial<{
    measure: string;
    dimension: string;
    time: string;
    geo: string;
  }>;
}

export interface DashboardRecord {
  id: string;
  title: string;
  folder?: string;
  ownerInitials: string;
  /** "Live" once it has at least one widget. */
  status: "live" | "stale" | "draft";
  /** Accent color CSS variable for the card stripe. */
  accent: string;
  /** ISO timestamp the dashboard was last edited. */
  updatedAt: string;
  /** Human label like "12s ago" computed at render time, not stored. */
  /** Headline metric shown on the list card. */
  headline?: { label: string; value: string; deltaDirection?: "up" | "down" };
  /** Optional sparkline values shown on the list card. */
  spark?: number[];
  /** Source template id when generated by smart-fill. */
  generatedFromTemplate?: string;
  widgets: DashboardWidget[];
}
